# Imagen base
FROM node:18

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos y dependencias
COPY package*.json ./
RUN npm install

COPY . .

# Exponer el puerto
EXPOSE 5000

# Iniciar el servidor
CMD ["npm", "run", "dev"]
